trigger:
  - chrpap-sf1-abuild

jobs:
  - job: Ubuntu_Build
    pool:
      vmImage: 'ubuntu-16.04'
  
    steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo 'ECHO: ' + $PWD
              echo 'ECHO: cd $HOME + ls'
              cd $HOME
              echo 'ECHO: ' + $PWD
              ls -la

              cd .azure
              ls -la
              cat az.json
              cat az.sess
              cat accessTokens.json

              echo 'ECHO: cd /tmp  + ls'
              cd /
              echo 'ECHO: $PWD ' $PWD
              ls -la

              cat azureProfile.json
              cat accessTokens.json
            addSpnToEnvironment: true