trigger:
  - chrpap-sf1-abuild

variables:
  DotNetCoreVersion: '2.1.503'
  
jobs:
  - job: Ubuntu_Build
    pool:
      vmImage: 'ubuntu-16.04'
  
    steps:
        - task: DotNetCoreInstaller@0
          displayName: 'Use .NET Core sdk $(DotNetCoreVersion)'
          inputs:
            version: '$(DotNetCoreVersion)'

        - task: AzureKeyVault@1
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            KeyVaultName: 'chrpap-secrets'
            SecretsFilter: '2dc1e421-5121-47e3-b411-36c8a35a35c8'
            RunAsPreJob: false

        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: './testsf_on_linux.sh'
            addSpnToEnvironment: true

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/*.trx'
            testRunTitle: 'Ubuntu Test Results'
            testResultsFormat: 'VSTest'
            mergeTestResults: true
            
