trigger:
  - chrpap-sf1-abuild

jobs:
  - job: build and tests
    pool:
      vmImage: 'windows-2019'
  
    steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '2.x'

        - task: AzureKeyVault@1
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            KeyVaultName: 'chrpap-secrets'
            SecretsFilter: '2dc1e421-5121-47e3-b411-36c8a35a35c8'
            RunAsPreJob: false

        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: './testsf_on_linux.sh'
            addSpnToEnvironment: true

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/*.trx'
            testRunTitle: 'Ubuntu Test Results'
            testResultsFormat: 'VSTest'
            mergeTestResults: true
            
