trigger:
  - chrpap-sf1-abuild

jobs:
  - job: build_and_tests
    pool:
      vmImage: 'ubuntu-16.04'
  
    steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '2.x'

        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Visual Studio Ultimate mit MSDN'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: './testsf_on_linux.sh'
            addSpnToEnvironment: true

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/*.trx'
            testRunTitle: 'Ubuntu Test Results'
            testResultsFormat: 'VSTest'
            mergeTestResults: true
            
